[package]
name = "day-23"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13"
rustc-hash = "2.1"
petgraph = "0.6"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
