[package]
name = "day-24"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13"
rand = "0.8"
rustc-hash = "2.1"
strum = { version = "0.26", features = ["derive"] }

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
